### ISSUE TITLE
wl_seat::get_pointer request issued on a seat without the pointer capability

### ISSUE THREAD

**Issue by st3r4g** [Smithay/client-toolkit#83] opened 2019-09-16 22:10 UTC
From https://wayland.freedesktop.org/docs/html/apa.html#protocol-spec-wl_seat:
> It is a protocol violation to issue this request on a seat that has never had the pointer capability.

Observed behaviour in `alacritty` and in the example clients (with WAYLAND_DEBUG=server):
```
[2601723.234] wl_registry@2.bind(4, "wl_seat", 5, new id [unknown]@27)
[2601723.259]  -> wl_seat@27.capabilities(2)
[2601723.267]  -> wl_seat@27.name("seat0")
[2601723.276] wl_compositor@3.create_surface(new id wl_surface@28)
[2601723.287] wl_seat@27.get_pointer(new id wl_pointer@29)
listener function for opcode 0 of wl_seat is NULL
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
The bitfield value 2 sent by the server in the capability event means that the seat has keyboards but not pointer or touch devices. It should be easy to request the creation of the appropriate protocol objects based on the capabilities sent by the server.

**Comment by vberger** [comment] 2019-09-17 11:56
Indeed, the `Window::new_seat()` method unconditionally binds the pointer, as such only seats with the pointer capability should be given to it. The examples (and I suspect winit) do not do that unfortunately.

**Comment by kchibisov** [comment] 2019-09-18 13:24
@st3r4g Would you mind running `RUST_BACKTRACE=1 alacritty`, so I can get a clue on what exactly kills it (there are two possible places, just checking)?

**Comment by st3r4g** [comment] 2019-09-18 13:36
The crash happens if the compositor sets to NULL the implementation of wl_seat::get_pointer (a compositor could choose not to support pointers). Actually can be easily circumvented by implementing the request in the compositor as a no-op, but anyway the spec is pretty explicit that it is an error (and many other clients do not call it).

**Comment by kchibisov** [comment] 2019-09-18 13:45
Probably `where` is much clearer than `what`, since `alacritty` uses multiple libraries for `Wayland` things, knowing the exact line of `unwrap` will speed up things a lot.

**Comment by st3r4g** [comment] 2019-09-18 13:49
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', src/libcore/result.rs:997:5
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
             at src/env/__libc_start_main.c:94
```
It seems I have to install some debug symbols. (Sorry, I'm not familiar with Rust)

**Comment by kchibisov** [comment] 2019-09-18 13:56
I guess you've installed it from your distro package, since alacritty by default builds in release + debug symbols. You can follow alacritty's INSTALL.md instructions for your distro to build it in debug, also compile this [PR](https://github.com/jwilm/alacritty/pull/2438) instead of master.

P.s.
You should open bug on alacritty bug tracker, so we'll keep alacritty related discussion in alacritty repo.

**Comment by st3r4g** [comment] 2019-09-18 14:46
I updated the backtrace. But why do you say this is an Alacritty bug? I thought the crash happened at the Rust `libwayland` implementation level as the compositor sets a function pointer to NULL and it gets called due to not following the protocol...

**Comment by vberger** [comment] 2019-09-18 14:48
> The crash happens if the compositor sets to NULL the implementation of wl_seat::get_pointer (a compositor could choose not to support pointers). Actually can be easily circumvented by implementing the request in the compositor as a no-op, but anyway the spec is pretty explicit that it is an error (and many other clients do not call it).

Note that setting NULL as the implementation of anything is a bug of the server though. A server should not crash due to ill-behaving clients, but rather detect protocol errors and kill the ill-behaving clients (with `wl_resource_post_error`).

In any case @kchibisov, both winit/SCTK *and* smithay-clipboard need to be fixed wrt to that.

For SCTK/winit, the issue is that `Window::new_seat(..)` unconditionally calls `get_pointer`. So we have two possibilities:

- Change winit so that is ony calls `Window::new_seat(..)` with seats that actually have the pointer capability
- Introduce some abstraction in SCTK to manage seats and handle this kind of questions automatically (this is quite related to #77)

**Comment by kchibisov** [comment] 2019-09-18 14:54
> But why do you say this is an Alacritty bug?

The bug is not in alacritty, that's right, I just wanted for us(alacritty) make it easier to track things, we're already has a lot of dependency bugs on our bug tracker. Anyway I can remember it or open myself.

@vberger Yeah, I see. As I said before on IRC to you, I'll try to fix `smithay-clipboard` one, hopefully on this week.

**Comment by vberger** [comment] 2020-01-17 12:03
This is fixed with the new refactor, as `Window` now automatically tracks seats without relying on outside help.

**Closed by vberger** 2020-01-17 12:03 UTC
